# Generated by Django 5.2.6 on 2025-09-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsRR_DB',
            fields=[
                ('Car_model', models.CharField(max_length=20)),
                ('Series', models.CharField()),
                ('Color', models.CharField(max_length=15)),
                ('Price', models.IntegerField(primary_key=True, serialize=False)),
                ('Fancy_number', models.IntegerField()),
            ],
        ),
    ]
